export function ConfirmationPage() {
  return (
    <div className="py-8 px-8">
      <h2 className="text-2xl text-gray-900 mb-6">5. 확인 및 유의사항</h2>

      <div className="space-y-6">
        <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
          <h3 className="text-gray-900 mb-3">문서 생성 정보</h3>
          <p className="text-gray-700 leading-relaxed mb-4">
            본 확인서는 <strong>AIFIXR 시스템</strong>을 통해
            협력사의 자가 응답을 기반으로 자동 생성되었으며,
            작성 시점의 관리 현황을 반영합니다.
          </p>
          <div className="grid grid-cols-2 gap-4 mt-4 pt-4 border-t border-gray-300">
            <div>
              <p className="text-sm text-gray-500 mb-1">데이터 출처</p>
              <p className="text-gray-900">Level 1 Action-based Checklist</p>
            </div>
            <div>
              <p className="text-sm text-gray-500 mb-1">생성 시스템</p>
              <p className="text-gray-900">AIFIXR Platform</p>
            </div>
          </div>
        </div>

        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
          <h3 className="text-blue-900 mb-3">문서의 성격</h3>
          <ul className="space-y-2">
            <li className="flex items-start gap-2 text-blue-800">
              <span className="text-blue-600 mt-1">✓</span>
              <span>공급망 ESG 관리 대응을 위한 <strong>증빙 문서</strong></span>
            </li>
            <li className="flex items-start gap-2 text-blue-800">
              <span className="text-blue-600 mt-1">✓</span>
              <span>협력사의 <strong>합리적 노력(Reasonable Effort)</strong>을 확인</span>
            </li>
            <li className="flex items-start gap-2 text-blue-800">
              <span className="text-blue-600 mt-1">✓</span>
              <span>대기업의 <strong>공급망 리스크 관리 책임</strong> 이행 근거</span>
            </li>
          </ul>
        </div>

        <div className="bg-red-50 border border-red-200 rounded-lg p-6">
          <h3 className="text-red-900 mb-3">본 문서가 아닌 것</h3>
          <ul className="space-y-2">
            <li className="flex items-start gap-2 text-red-800">
              <span className="text-red-600 mt-1">✕</span>
              <span>ESG 평가 보고서 또는 등급 자료가 <strong>아닙니다</strong></span>
            </li>
            <li className="flex items-start gap-2 text-red-800">
              <span className="text-red-600 mt-1">✕</span>
              <span>ESG 공시 또는 지속가능경영 보고서가 <strong>아닙니다</strong></span>
            </li>
            <li className="flex items-start gap-2 text-red-800">
              <span className="text-red-600 mt-1">✕</span>
              <span>협력사 간 비교 또는 순위 자료가 <strong>아닙니다</strong></span>
            </li>
          </ul>
        </div>

        <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
          <h3 className="text-gray-900 mb-3">추가 유의사항</h3>
          <p className="text-gray-700 leading-relaxed mb-3">
            본 확인서의 내용은 협력사가 체크리스트에 응답한 시점의 정보를 기반으로 하며,
            향후 관리 체계 변화에 따라 내용이 달라질 수 있습니다.
          </p>
          <p className="text-gray-700 leading-relaxed">
            대기업은 본 문서를 근거로 공급망 ESG 리스크 관리 활동을 수행하고 있음을 설명할 수 있으며,
            필요 시 협력사와 함께 단계적 개선 계획을 수립할 수 있습니다.
          </p>
        </div>
      </div>

      {/* Footer */}
      <div className="mt-12 pt-6 border-t border-gray-300 text-center">
        <div className="flex items-center justify-center gap-2 mb-2">
          <div className="bg-gradient-to-br from-blue-600 to-indigo-700 px-3 py-1 rounded">
            <span className="text-white text-sm tracking-wider">AIFIXR</span>
          </div>
        </div>
        <p className="text-sm text-gray-500">Generated by AIFIXR Platform</p>
        <p className="text-sm text-gray-500">ESG Supply Chain Management Solution</p>
        <p className="text-xs text-gray-400 mt-2">Not an ESG rating or disclosure document</p>
      </div>
    </div>
  );
}

